### ISSUE TITLE
Submission Assignment-1

### ISSUE THREAD

**Issue by zhamri** [STIW3054-A191/Assignments#1]
# If completed, paste your Assignment-1 REPOSITORY link here.

**Comment by TanChengYi** [comment]
https://github.com/TanChengYi/253814-STIW3054-A191-A1

**Comment by Quitetve** [comment]
https://github.com/Quitetve/256510-STIW3054-A191-A1

**Comment by Quitetve** [comment]
https://github.com/Quitetve/256510-STIW3054-A191-A1

**Comment by OXunSheng** [comment]
https://github.com/OXunSheng/253881-STIW3054-A191-A1

**Comment by PhuahMeiQi** [comment]
https://github.com/PhuahMeiQi/259501-STIW3054-A191-A1

**Comment by jasonway96** [comment]
https://github.com/jasonway96/256750-STIW3054-A191-A1

**Comment by sohcheefung** [comment]
https://github.com/sohcheefung/259521-STIW3054-A191-A1

**Comment by weiditan** [comment]
https://github.com/weiditan/259296-STIW3054-A191-A1

**Comment by ychian234** [comment]
https://github.com/ychian234/259187-STIW3054-A191-A1

**Comment by yeongshyhhaw** [comment]
https://github.com/yeongshyhhaw/254772-STIW3054-A191-A1

**Comment by fazlizam96** [comment]
https://github.com/fazlizam96/259132-STIW3054-A191-A1

**Comment by macasyraf** [comment]
https://github.com/macasyraf/256599-STIW3054-A191-A1

**Comment by muhdhariz** [comment]
https://github.com/muhdhariz/256549-STIW3054-A191-A1

**Comment by vissanuck** [comment]
https://github.com/vissanuck/256609-STIW3054-A191-A1

**Comment by AhmedBawazir2020** [comment]
https://github.com/AhmedBawazir2020/249879-STIW3054-A191-A1.git

**Comment by WwLuo-1024** [comment]
https://github.com/WwLuo-1024/251230-STIW3054-A191-A1

**Comment by thineshsubramani** [comment]
https://github.com/thinesh40/254423-STIW3054-A191-A1

**Comment by farisleh** [comment]
https://github.com/farisleh/255312-STIW3054-A191-A1

**Comment by sufyankamal** [comment]
https://github.com/sufyankamal/255541-STIW3054-A191-A1

**Comment by SilentHlive** [comment]
https://github.com/SilentHlive/255227-STIW3054-A191-A1

**Comment by yyjmax** [comment]
https://github.com/yyjmax/243147-STIW3054-A191-Assignment1

**Comment by Gv3N** [comment]
https://github.com/Gv3N/252709-STIW3054-A191-A1

**Comment by liviniesh** [comment]
https://github.com/liviniesh/255101-STIW3054-A191-A1

**Comment by chinsfuh** [comment]
https://github.com/chinsfuh/2566432-STIW3054-A191-A1

**Comment by aidqayyum** [comment]
https://github.com/aidqayyum/253288-STIW3054-A191-A1

**Comment by coNNectGan** [comment]
https://github.com/coNNectGan/255108-STIW3054-A191-A1

**Comment by peipei28** [comment]
https://github.com/peipei28/Assignment

**Comment by peipei28** [comment]
https://github.com/peipei28/254251-STIW3054-A191-A1

**Comment by prayat15** [comment]
https://github.com/prayat15/250615-STIW3054-A191-A1

**Comment by Nurshafiqahdiela** [comment]
https://github.com/Nurshafiqahdiela/259383-STIW3054-A191-A1-A1

**Comment by zhamri** [comment]
> https://github.com/TanChengYi/253814-STIW3054-A191-A1

TotalClass: 12
TotalMean: 22.916666666666664
TotalMedian: 19.5
TotalStdDev: 15.37
TotalMin: 10.0
TotalMax: 60.0
TotalSum: 275.0

**Comment by zhamri** [comment]
> https://github.com/OXunSheng/253881-STIW3054-A191-A1

TotalClass: 13
TotalMean: 30.846153846153847
TotalMedian: 25.0
TotalStdDev: 27.30
TotalMin: 4.0
TotalMax: 103.0
TotalSum: 401.0

**Comment by zhamri** [comment]
> https://github.com/PhuahMeiQi/259501-STIW3054-A191-A1

TotalClass: 11
TotalMean: 32.63636363636363
TotalMedian: 19.0
TotalStdDev: 26.36
TotalMin: 5.0
TotalMax: 79.0
TotalSum: 359.0

**Comment by zhamri** [comment]
> https://github.com/weiditan/259296-STIW3054-A191-A1

TotalClass: 11
TotalMean: 30.454545454545453
TotalMedian: 30.0
TotalStdDev: 29.83
TotalMin: 0.0
TotalMax: 85.0
TotalSum: 335.0

**Comment by zhamri** [comment]
> https://github.com/ychian234/259187-STIW3054-A191-A1

TotalClass: 2
TotalMean: 53.0
TotalMedian: 53.0
TotalStdDev: 42.43
TotalMin: 23.0
TotalMax: 83.0
TotalSum: 106.0

**Comment by zhamri** [comment]
> https://github.com/yeongshyhhaw/254772-STIW3054-A191-A1

TotalClass: 6
TotalMean: 45.166666666666664
TotalMedian: 35.0
TotalStdDev: 32.32
TotalMin: 18.0
TotalMax: 102.0
TotalSum: 271.0

**Comment by zhamri** [comment]
> https://github.com/macasyraf/256599-STIW3054-A191-A1

TotalClass: 5
TotalMean: 29.200000000000003
TotalMedian: 32.0
TotalStdDev: 13.41
TotalMin: 9.0
TotalMax: 41.0
TotalSum: 146.0

**Comment by zhamri** [comment]
> https://github.com/muhdhariz/256549-STIW3054-A191-A1

TotalClass: 6
TotalMean: 28.333333333333332
TotalMedian: 31.0
TotalStdDev: 17.90
TotalMin: 7.0
TotalMax: 53.0
TotalSum: 170.0

**Comment by zhamri** [comment]
> https://github.com/vissanuck/256609-STIW3054-A191-A1

TotalClass: 5
TotalMean: 30.8
TotalMedian: 35.0
TotalStdDev: 12.77
TotalMin: 11.0
TotalMax: 42.0
TotalSum: 154.0

**Comment by zhamri** [comment]
> https://github.com/AhmedBawazir2020/249879-STIW3054-A191-A1.git

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.186 s
[INFO] Finished at: 2020-01-01T15:56:56+08:00
[INFO] Final Memory: 5M/27M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Volumes/Data/Students/STIW3054-RT/A191/Assignment-1/249879-STIW3054-A191-A1). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by zhamri** [comment]
> https://github.com/WwLuo-1024/251230-STIW3054-A191-A1

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:29 min
[INFO] Finished at: 2020-01-01T16:05:43+08:00
[INFO] Final Memory: 21M/50M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project RealTimeAssignemnt: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] 
[ERROR] 
[ERROR] An annotation processor threw an uncaught exception.
[ERROR] Consult the following stack trace for details.
[ERROR] java.lang.ExceptionInInitializerError

**Comment by zhamri** [comment]
> https://github.com/thinesh40/254423-STIW3054-A191-A1

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:30 min
[INFO] Finished at: 2020-01-01T16:14:14+08:00
[INFO] Final Memory: 14M/49M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project 254423-STIW3054-A191-A1: Compilation failure: Compilation failure:

**Comment by zhamri** [comment]
> https://github.com/farisleh/255312-STIW3054-A191-A1

TotalClass: 7
TotalMean: 28.71428571428571
TotalMedian: 28.0
TotalStdDev: 16.06
TotalMin: 10.0
TotalMax: 57.0
TotalSum: 201.0

**Comment by zhamri** [comment]
> https://github.com/sufyankamal/255541-STIW3054-A191-A1

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.207 s
[INFO] Finished at: 2020-01-01T16:21:25+08:00
[INFO] Final Memory: 5M/27M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Volumes/Data/Students/STIW3054-RT/A191/Assignment-1/255541-STIW3054-A191-A1). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by zhamri** [comment]
> https://github.com/SilentHlive/255227-STIW3054-A191-A1

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.089 s
[INFO] Finished at: 2020-01-01T16:23:40+08:00
[INFO] Final Memory: 5M/27M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Volumes/Data/Students/STIW3054-RT/A191/Assignment-1/255227-STIW3054-A191-A1). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by zhamri** [comment]
> https://github.com/yyjmax/243147-STIW3054-A191-Assignment1

java.io.FileNotFoundException: /Volumes/Data/Students/STIW3054-RT/A191/Assignment-1/243147-STIW3054-A191-A1/target/classes/CKJMResultz.txt (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at java.base/java.util.Scanner.<init>(Scanner.java:639)
	at my.zhamri.ConvertTxtToCsv.go(ConvertTxtToCsv.java:11)
	at my.zhamri.Main.main(Main.java:35)

TotalClass: 2
TotalMean: 77.0
TotalMedian: 77.0
TotalStdDev: 60.81
TotalMin: 34.0
TotalMax: 120.0
TotalSum: 154.0

**Comment by zhamri** [comment]
> https://github.com/Gv3N/252709-STIW3054-A191-A1

TotalClass: 5
TotalMean: 30.6
TotalMedian: 35.0
TotalStdDev: 12.64
TotalMin: 11.0
TotalMax: 42.0
TotalSum: 153.0

**Comment by zhamri** [comment]
> https://github.com/liviniesh/255101-STIW3054-A191-A1

TotalClass: 10
TotalMean: 23.0
TotalMedian: 25.0
TotalStdDev: 11.19
TotalMin: 9.0
TotalMax: 43.0
TotalSum: 230.0

**Comment by zhamri** [comment]
> https://github.com/aidqayyum/253288-STIW3054-A191-A1

TotalClass: 6
TotalMean: 27.499999999999996
TotalMedian: 26.5
TotalStdDev: 17.23
TotalMin: 10.0
TotalMax: 56.0
TotalSum: 165.0

**Comment by zhamri** [comment]
> https://github.com/coNNectGan/255108-STIW3054-A191-A1

TotalClass: 6
TotalMean: 30.166666666666668
TotalMedian: 31.5
TotalStdDev: 18.51
TotalMin: 10.0
TotalMax: 57.0
TotalSum: 181.0

**Comment by zhamri** [comment]
> https://github.com/prayat15/250615-STIW3054-A191-A1

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.866 s
[INFO] Finished at: 2020-01-01T17:07:06+08:00
[INFO] Final Memory: 5M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Volumes/Data/Students/STIW3054-RT/A191/Assignment-1/250615-STIW3054-A191-A1). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by zhamri** [comment]
> https://github.com/Nurshafiqahdiela/259383-STIW3054-A191-A1-A1

java.io.FileNotFoundException: /Volumes/Data/Students/STIW3054-RT/A191/Assignment-1/259383-STIW3054-A191-A1/target/classes/CKJMResultz.txt (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at java.base/java.util.Scanner.<init>(Scanner.java:639)
	at my.zhamri.ConvertTxtToCsv.go(ConvertTxtToCsv.java:11)
	at my.zhamri.Main.main(Main.java:36)

**Comment by FatihahFauzi** [comment]
https://github.com/FatihahFauzi/245607-STIW3054-A191-A1

**Comment by zhamri** [comment]
> https://github.com/FatihahFauzi/245607-STIW3054-A191-A1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.032 s
[INFO] Finished at: 2020-01-02T10:28:58+08:00
[INFO] Final Memory: 9M/37M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Individul: Compilation failure: Compilation failure: 
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
